"""Initial schema: conversations, messages, tasks, events_outbox, api_keys, audit_log.

PostgreSQL additionally gets two triggers: the task transition guard from the Task Engine
reference §9.3 and an append-only guard on audit_log. SQLite (development/tests) relies on
the same rules enforced in application code.

Revision ID: 0001
Revises:
Create Date: 2026-10-01
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


TASKS_GUARD_SQL = (
    """
CREATE FUNCTION tasks_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.status <> OLD.status AND (OLD.status, NEW.status) NOT IN (
     ('queued','running'),('queued','cancelled'),
     ('running','succeeded'),('running','failed'),('running','cancelled'),
     ('running','queued'),('running','waiting'),('running','dead'),
     ('waiting','queued'),('waiting','running'),('waiting','cancelled'),
     ('queued','failed'),('waiting','failed'),
     ('failed','queued'),('dead','queued')) THEN
    RAISE EXCEPTION 'illegal task transition % -> %', OLD.status, NEW.status
      USING ERRCODE = 'check_violation';
  END IF;
  IF NEW.status <> 'running' THEN NEW.lease_owner := NULL; NEW.lease_until := NULL; END IF;
  RETURN NEW;
END $$
""",
    "CREATE TRIGGER tasks_guard BEFORE UPDATE OF status ON tasks FOR EACH ROW EXECUTE FUNCTION tasks_guard()",
)

AUDIT_APPEND_ONLY_SQL = (
    """
CREATE FUNCTION audit_log_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'audit_log is append-only' USING ERRCODE = 'insufficient_privilege';
END $$
""",
    "CREATE TRIGGER audit_log_append_only BEFORE UPDATE OR DELETE ON audit_log "
    "FOR EACH ROW EXECUTE FUNCTION audit_log_append_only()",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_keys",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("key_prefix", sa.String(length=24), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "roles", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
        sa.UniqueConstraint("key_hash", name=op.f("uq_api_keys_key_hash")),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("actor_type", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.String(length=80), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("target", sa.String(length=80), nullable=True),
        sa.Column(
            "details", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_log_action"), ["action"], unique=False)

    op.create_table(
        "conversations",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("customer_id", sa.String(length=40), nullable=True),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("agent_profile", sa.String(length=64), nullable=False),
        sa.Column("handed_off_to", sa.String(length=40), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("summary_upto_message_id", sa.String(length=40), nullable=True),
        sa.Column("msg_seq", sa.Integer(), nullable=False),
        sa.Column("last_user_seq", sa.Integer(), nullable=False),
        sa.Column("answered_through_seq", sa.Integer(), nullable=False),
        sa.Column(
            "metadata", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("channel IN ('web', 'sms', 'api')", name=op.f("ck_conversations_channel")),
        sa.CheckConstraint("status IN ('open', 'closed')", name=op.f("ck_conversations_status")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
    )
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_conversations_customer_id"), ["customer_id"], unique=False)

    op.create_table(
        "events_outbox",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("version", sa.SmallInteger(), nullable=False),
        sa.Column(
            "subject", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column(
            "data", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events_outbox")),
    )
    with op.batch_alter_table("events_outbox", schema=None) as batch_op:
        batch_op.create_index(
            "ix_events_outbox_pending",
            ["occurred_at"],
            unique=False,
            postgresql_where=sa.text("dispatched_at IS NULL"),
            sqlite_where=sa.text("dispatched_at IS NULL"),
        )
        batch_op.create_index(batch_op.f("ix_events_outbox_type"), ["type"], unique=False)

    op.create_table(
        "tasks",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("kind_version", sa.SmallInteger(), nullable=False),
        sa.Column("lane", sa.SmallInteger(), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("run_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_token", sa.BigInteger(), nullable=False),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("total_failures", sa.Integer(), nullable=False),
        sa.Column("concurrency_key", sa.String(length=128), nullable=True),
        sa.Column("dedupe_key", sa.String(length=200), nullable=True),
        sa.Column("parent_task_id", sa.String(length=40), nullable=True),
        sa.Column("conversation_id", sa.String(length=40), nullable=True),
        sa.Column("customer_id", sa.String(length=40), nullable=True),
        sa.Column("lead_id", sa.String(length=40), nullable=True),
        sa.Column(
            "input", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column(
            "state", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column(
            "result", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column(
            "last_error", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column(
            "progress", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("emit_events", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'running') = (lease_owner IS NOT NULL AND lease_until IS NOT NULL)", name=op.f("ck_tasks_lease")
        ),
        sa.CheckConstraint("mode IN ('immediate', 'background', 'scheduled')", name=op.f("ck_tasks_mode")),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'waiting', 'succeeded', 'failed', 'cancelled', 'dead')",
            name=op.f("ck_tasks_status"),
        ),
        sa.CheckConstraint("lane BETWEEN 0 AND 3", name=op.f("ck_tasks_lane")),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_tasks_conversation_id_conversations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["parent_task_id"], ["tasks.id"], name=op.f("fk_tasks_parent_task_id_tasks"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_tasks_dedupe_key")),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index("ix_tasks_conversation_id_status", ["conversation_id", "status"], unique=False)
        batch_op.create_index("ix_tasks_lane_run_at", ["lane", "run_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_tasks_parent_task_id"), ["parent_task_id"], unique=False)
        batch_op.create_index(
            "tasks_one_running_per_key",
            ["concurrency_key"],
            unique=True,
            postgresql_where=sa.text("status = 'running' AND concurrency_key IS NOT NULL"),
            sqlite_where=sa.text("status = 'running' AND concurrency_key IS NOT NULL"),
        )

    op.create_table(
        "messages",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("conversation_id", sa.String(length=40), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("channel_msg_id", sa.String(length=128), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("task_id", sa.String(length=40), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("tokens_in", sa.Integer(), nullable=True),
        sa.Column("tokens_out", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("role IN ('user', 'assistant', 'system')", name=op.f("ck_messages_role")),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], name=op.f("fk_messages_task_id_tasks"), ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint("conversation_id", "seq", name=op.f("uq_messages_conversation_id_seq")),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_messages_task_id"), ["task_id"], unique=False)
        batch_op.create_index(
            "uq_messages_conversation_id_channel_msg_id",
            ["conversation_id", "channel_msg_id"],
            unique=True,
            postgresql_where=sa.text("channel_msg_id IS NOT NULL"),
            sqlite_where=sa.text("channel_msg_id IS NOT NULL"),
        )

    if op.get_bind().dialect.name == "postgresql":
        for statement in (*TASKS_GUARD_SQL, *AUDIT_APPEND_ONLY_SQL):
            op.execute(statement)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS tasks_guard ON tasks")
        op.execute("DROP FUNCTION IF EXISTS tasks_guard()")
        op.execute("DROP TRIGGER IF EXISTS audit_log_append_only ON audit_log")
        op.execute("DROP FUNCTION IF EXISTS audit_log_append_only()")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_messages_conversation_id_channel_msg_id",
            postgresql_where=sa.text("channel_msg_id IS NOT NULL"),
            sqlite_where=sa.text("channel_msg_id IS NOT NULL"),
        )
        batch_op.drop_index(batch_op.f("ix_messages_task_id"))

    op.drop_table("messages")
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index(
            "tasks_one_running_per_key",
            postgresql_where=sa.text("status = 'running' AND concurrency_key IS NOT NULL"),
            sqlite_where=sa.text("status = 'running' AND concurrency_key IS NOT NULL"),
        )
        batch_op.drop_index(batch_op.f("ix_tasks_parent_task_id"))
        batch_op.drop_index("ix_tasks_lane_run_at")
        batch_op.drop_index("ix_tasks_conversation_id_status")

    op.drop_table("tasks")
    with op.batch_alter_table("events_outbox", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_outbox_type"))
        batch_op.drop_index(
            "ix_events_outbox_pending",
            postgresql_where=sa.text("dispatched_at IS NULL"),
            sqlite_where=sa.text("dispatched_at IS NULL"),
        )

    op.drop_table("events_outbox")
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversations_customer_id"))

    op.drop_table("conversations")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_action"))

    op.drop_table("audit_log")
    op.drop_table("api_keys")
    # ### end Alembic commands ###
