"""Phase 2: task_steps, tool_executions, approvals, side_effects (ledger), llm_usage;
tasks.wait_kind / wait_ref / step_count.

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-01
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "approvals",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("task_id", sa.String(length=40), nullable=False),
        sa.Column("step_no", sa.Integer(), nullable=False),
        sa.Column("execution_id", sa.String(length=40), nullable=True),
        sa.Column("conversation_id", sa.String(length=40), nullable=True),
        sa.Column("tool_name", sa.String(length=128), nullable=False),
        sa.Column("tool_version", sa.String(length=16), nullable=False),
        sa.Column("risk_level", sa.String(length=10), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column(
            "sanitized_input",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("requested_by", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_by", sa.String(length=80), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_note", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected', 'expired', 'cancelled')", name=op.f("ck_approvals_status")
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], name=op.f("fk_approvals_task_id_tasks"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
    )
    with op.batch_alter_table("approvals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_approvals_conversation_id"), ["conversation_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_approvals_task_id"), ["task_id"], unique=False)
        batch_op.create_index(
            "uq_approvals_pending_step",
            ["task_id", "step_no"],
            unique=True,
            postgresql_where=sa.text("status = 'pending'"),
            sqlite_where=sa.text("status = 'pending'"),
        )

    op.create_table(
        "llm_usage",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("task_id", sa.String(length=40), nullable=True),
        sa.Column("conversation_id", sa.String(length=40), nullable=True),
        sa.Column("step_no", sa.Integer(), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("tier", sa.String(length=16), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error_type", sa.String(length=64), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("estimated_cost", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_llm_usage_task_id_tasks"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_usage")),
    )
    with op.batch_alter_table("llm_usage", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_llm_usage_conversation_id"), ["conversation_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_llm_usage_task_id"), ["task_id"], unique=False)

    op.create_table(
        "side_effects",
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("task_id", sa.String(length=40), nullable=True),
        sa.Column("step_no", sa.Integer(), nullable=True),
        sa.Column("execution_id", sa.String(length=40), nullable=True),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("provider_ref", sa.String(length=128), nullable=True),
        sa.Column(
            "response", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'succeeded', 'failed', 'unknown')", name=op.f("ck_side_effects_status")
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_side_effects_task_id_tasks"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("idempotency_key", name=op.f("pk_side_effects")),
    )
    op.create_table(
        "task_steps",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("task_id", sa.String(length=40), nullable=False),
        sa.Column("step_no", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("tool_call_id", sa.String(length=80), nullable=True),
        sa.Column(
            "input", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column(
            "output", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column("error_type", sa.String(length=32), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("execution_id", sa.String(length=40), nullable=True),
        sa.Column("approval_id", sa.String(length=40), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'succeeded', 'failed', 'cancelled', 'waiting_approval', 'skipped')",
            name=op.f("ck_task_steps_status"),
        ),
        sa.CheckConstraint("type IN ('model_call', 'tool_call')", name=op.f("ck_task_steps_type")),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_task_steps_task_id_tasks"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_steps")),
        sa.UniqueConstraint("task_id", "step_no", name=op.f("uq_task_steps_task_id_step_no")),
    )
    op.create_table(
        "tool_executions",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("task_id", sa.String(length=40), nullable=True),
        sa.Column("step_no", sa.Integer(), nullable=True),
        sa.Column("conversation_id", sa.String(length=40), nullable=True),
        sa.Column("tool_name", sa.String(length=128), nullable=False),
        sa.Column("tool_version", sa.String(length=16), nullable=False),
        sa.Column("actor_type", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.String(length=80), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "sanitized_input",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("output_status", sa.String(length=20), nullable=False),
        sa.Column(
            "output", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column("error_type", sa.String(length=32), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("policy_decision", sa.String(length=20), nullable=True),
        sa.Column("risk_level", sa.String(length=10), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("approval_id", sa.String(length=40), nullable=True),
        sa.Column("idempotency_key", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "error_type IS NULL OR error_type IN ('validation_error', 'authorization_error', 'policy_denied', 'approval_required', 'timeout', 'provider_error', 'network_error', 'business_error', 'unknown_error')",
            name=op.f("ck_tool_executions_error_type"),
        ),
        sa.CheckConstraint(
            "output_status IN ('pending', 'running', 'succeeded', 'failed', 'denied', 'waiting_approval', 'cancelled')",
            name=op.f("ck_tool_executions_output_status"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_tool_executions_task_id_tasks"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_executions")),
    )
    with op.batch_alter_table("tool_executions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tool_executions_conversation_id"), ["conversation_id"], unique=False)
        batch_op.create_index("uq_tool_executions_task_id_step_no", ["task_id", "step_no"], unique=True)
        batch_op.create_index(batch_op.f("ix_tool_executions_tool_name"), ["tool_name"], unique=False)
        batch_op.create_index(
            "uq_tool_executions_succeeded_key",
            ["idempotency_key"],
            unique=True,
            postgresql_where=sa.text("output_status = 'succeeded' AND idempotency_key IS NOT NULL"),
            sqlite_where=sa.text("output_status = 'succeeded' AND idempotency_key IS NOT NULL"),
        )

    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("wait_kind", sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column("wait_ref", sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column("step_count", sa.Integer(), nullable=False, server_default="0"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_column("step_count")
        batch_op.drop_column("wait_ref")
        batch_op.drop_column("wait_kind")

    with op.batch_alter_table("tool_executions", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_tool_executions_succeeded_key",
            postgresql_where=sa.text("output_status = 'succeeded' AND idempotency_key IS NOT NULL"),
            sqlite_where=sa.text("output_status = 'succeeded' AND idempotency_key IS NOT NULL"),
        )
        batch_op.drop_index(batch_op.f("ix_tool_executions_tool_name"))
        batch_op.drop_index("uq_tool_executions_task_id_step_no")
        batch_op.drop_index(batch_op.f("ix_tool_executions_conversation_id"))

    op.drop_table("tool_executions")
    op.drop_table("task_steps")
    op.drop_table("side_effects")
    with op.batch_alter_table("llm_usage", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_llm_usage_task_id"))
        batch_op.drop_index(batch_op.f("ix_llm_usage_conversation_id"))

    op.drop_table("llm_usage")
    with op.batch_alter_table("approvals", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_approvals_pending_step",
            postgresql_where=sa.text("status = 'pending'"),
            sqlite_where=sa.text("status = 'pending'"),
        )
        batch_op.drop_index(batch_op.f("ix_approvals_task_id"))
        batch_op.drop_index(batch_op.f("ix_approvals_conversation_id"))

    op.drop_table("approvals")
    # ### end Alembic commands ###
