const { chromium } = require('playwright')
const assert = require('node:assert/strict')
;(async () => {
 const browser = await chromium.launch({headless:true})
 const errors = []
 const page = await browser.newPage({viewport:{width:1440,height:1100}})
 page.on('pageerror', e=>errors.push(e.message))
 page.on('console', m=>{if((m.type()==='warning' || m.type()==='error') && !m.text().startsWith('You have Reduced Motion enabled')) errors.push(m.text())})
 await page.route('https://fonts.googleapis.com/**', r=>r.fulfill({contentType:'text/css',body:''}))
 const S = {weights:{lead:5,pre:10,funnel:20,follow:15,close:35,post:10,fin:5},officialDeduct:10,months:{}}
 const deals = Array.from({length:4}, (_,i)=>({id:i+1,no:`N-${i+1}`,name:`مشتری ${i+1}`,month:0,amount:'100000000',funnel:['start','qualify','advance','won'][i],settle:'check',stages:['lead','pre','funnel','follow','close','post','fin'],kind:'new',channel:'official',fy:'1405'}))
 const full = {fy:'1405',gid:20,years:{1405:{}},people:[{id:1,name:'آزمایش',role:'sales',S,inv:deals,invY:{1405:deals}},{id:2,name:'غیرفعال',inactive:true,S,inv:[],invY:{1405:[]}}],importLog:[{ts:1,name:'history.xlsx',type:'deal',rows:4,routed:true,sig:'old'}]}
 let saved = [], failSave = false, writes = []
 await page.route('**/api/**', async r=>{
  const url=new URL(r.request().url())
  if(url.pathname==='/api/ui-layout') {
   if(r.request().method()==='POST') {
    const body=r.request().postDataJSON();writes.push(body)
    if(failSave) {failSave=false;return r.fulfill({status:500,json:{ok:false}})}
    if(body.list.startsWith('ledger.rows')) saved=body.order
    return r.fulfill({json:{ok:true}})
   }
   return r.fulfill({json:{ok:true,order:url.searchParams.get('list').startsWith('ledger.rows')?saved:[]}})
  }
  if(url.pathname==='/api/state') return r.fulfill({json:{ok:true,full}})
  return r.fulfill({json:{ok:true}})
 })
 await page.route('**/legacy?*',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><title>Local test bridge</title>'}))
 const url='http://127.0.0.1:5183/tests/browser/index.html'
 await page.goto(url+'?view=funnel')
 const paths=page.locator('svg[aria-label="قیف تبدیل فروش"] path')
 await paths.first().waitFor()
 await page.waitForTimeout(800)
 const d0=await paths.nth(1).getAttribute('d')
 await paths.nth(1).evaluate(el=>{el.dataset.sameNode='yes'})
 const legends=page.getByRole('list',{name:'راهنمای قیف'}).getByRole('button')
 await legends.nth(1).focus()
 assert.equal(await paths.nth(1).getAttribute('aria-pressed'),'true')
 await paths.nth(2).focus()
 assert.equal(await legends.nth(2).getAttribute('aria-pressed'),'true')
 await page.getByRole('button',{name:'تغییر داده'}).click()
 await page.waitForTimeout(450)
 assert.notEqual(await paths.nth(1).getAttribute('d'),d0)
 assert.equal(await paths.nth(1).getAttribute('data-same-node'),'yes')
 for(const theme of ['blue','purple','gold']) for(const mode of ['light','dark']) {
  await page.evaluate(({theme,mode})=>{document.documentElement.dataset.theme=theme;document.documentElement.dataset.mode=mode},{theme,mode})
  const fill=await paths.first().evaluate(el=>getComputedStyle(el).fill)
  assert.match(fill,/rgb/)
 }
 await page.emulateMedia({reducedMotion:'reduce'})
 await page.reload();await paths.first().waitFor()
 assert.ok((await paths.first().getAttribute('d')).includes('20'))
 await page.goto(url)
 await page.getByRole('grid').waitFor()
 assert.equal(await page.getByRole('combobox',{name:'کارشناس فعال'}).locator('option').filter({hasText:'غیرفعال'}).count(),0)
 assert.equal(await page.getByRole('columnheader',{name:'پیگیری',exact:true}).count(),0)
 let rows=page.locator('[data-order-row]')
 const first=await rows.first().getAttribute('data-order-row')
 const grip=rows.first().getByRole('button',{name:'جابه‌جایی ردیف؛ بکشید یا کلید بالا و پایین'})
 await grip.focus();await grip.press('ArrowDown')
 await page.waitForTimeout(180)
 assert.notEqual(await rows.first().getAttribute('data-order-row'),first)
 assert.ok(saved.length===4)
 await page.reload();await rows.first().waitFor()
 assert.equal(await rows.first().getAttribute('data-order-row'),saved[0])
 const before=await rows.evaluateAll(es=>es.map(e=>e.dataset.orderRow))
 failSave=true
 await rows.first().getByRole('button',{name:'جابه‌جایی ردیف؛ بکشید یا کلید بالا و پایین'}).press('ArrowDown')
 await page.waitForTimeout(220)
 assert.deepEqual(await rows.evaluateAll(es=>es.map(e=>e.dataset.orderRow)),before)
 // Mouse drag uses the existing pointer-event pattern and never triggers row actions.
 const dragBefore = await rows.first().getAttribute('data-order-row')
 await rows.first().evaluate(el=>el.scrollIntoView({block:'start'}))
 const from = await rows.first().getByRole('button',{name:'جابه‌جایی ردیف؛ بکشید یا کلید بالا و پایین'}).boundingBox()
 const to = await rows.nth(2).getByRole('button',{name:'جابه‌جایی ردیف؛ بکشید یا کلید بالا و پایین'}).boundingBox()
 await page.mouse.move(from.x+from.width/2,from.y+from.height/2); await page.mouse.down()
 await page.mouse.move(to.x+to.width/2,to.y+to.height/2,{steps:5});await page.mouse.up()
 await page.waitForTimeout(180)
 assert.notEqual(await rows.first().getAttribute('data-order-row'),dragBefore)
 // Remove the expected failed-response browser diagnostic from the deliberate rollback test.
 const unexpected=errors.filter(e=>!e.includes('500 (Internal Server Error)'))
 assert.deepEqual(unexpected,[])
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(150)
 assert.equal(await page.getByRole('grid').count(),0)
 assert.ok(await page.locator('[data-order-row]').count()>0)
 const touchFirst = await rows.first().getAttribute('data-order-row')
 await rows.first().evaluate(el=>el.scrollIntoView({block:'start'}))
 // Touch pointers follow the same controller; cancellation must not save.
 const touchGrip = rows.first().getByRole('button',{name:'جابه‌جایی ردیف؛ بکشید یا کلید بالا و پایین'})
 await touchGrip.dispatchEvent('pointerdown',{button:0,pointerType:'touch',pointerId:2})
 await page.evaluate(()=>window.dispatchEvent(new PointerEvent('pointercancel',{pointerType:'touch',pointerId:2})))
 assert.equal(await rows.first().getAttribute('data-order-row'),touchFirst)
 const touchFrom = await touchGrip.boundingBox()
 const touchTo = await rows.nth(1).getByRole('button',{name:'جابه‌جایی ردیف؛ بکشید یا کلید بالا و پایین'}).boundingBox()
 const cdp = await page.context().newCDPSession(page)
 await cdp.send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:1})
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:touchFrom.x+touchFrom.width/2,y:touchFrom.y+touchFrom.height/2}]})
 await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:touchTo.x+touchTo.width/2,y:touchTo.y+touchTo.height/2}]})
 await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]})
 await page.waitForTimeout(180)
 assert.notEqual(await rows.first().getAttribute('data-order-row'),touchFirst)
 await page.screenshot({path:'/workspace/scratch/ledger-mobile.png',fullPage:true})
 await page.goto(url+'?view=import')
 await page.getByText('history.xlsx',{exact:true}).waitFor()
 assert.equal(await page.getByRole('button',{name:'حذف تاریخچهٔ history.xlsx'}).count(),1)
 const csv=Buffer.from('مرحله,ارزش,شرکت,سال مالی,معامله,تاریخ\nبستن,1000,آزمایش,1405,N1,1405/01/01')
 await page.locator('input[type=file]').first().setInputFiles([{name:'one.csv',mimeType:'text/csv',buffer:csv},{name:'two.csv',mimeType:'text/csv',buffer:csv},{name:'bad.txt',mimeType:'text/plain',buffer:Buffer.from('bad')}])
 await page.getByText('فایل تکراری در صف — وارد نمی‌شود',{exact:true}).waitFor()
 assert.equal(await page.getByRole('button',{name:'حذف از صف'}).count(),3)
 await page.getByRole('button',{name:'حذف از صف'}).first().click()
 assert.equal(await page.getByRole('button',{name:'حذف از صف'}).count(),2)
 assert.equal(await page.getByText('فایل تکراری در صف — وارد نمی‌شود',{exact:true}).count(),0)
 await page.goto(url+'?view=import&role=sales')
 await page.getByText('history.xlsx',{exact:true}).waitFor()
 assert.equal(await page.getByRole('button',{name:'حذف تاریخچهٔ history.xlsx'}).count(),0)
 assert.deepEqual(errors.filter(e=>!e.includes('500 (Internal Server Error)')),[])
 console.log('PASS: funnel geometry/morph/shared focus/6 themes/reduced motion; ledger selection/keyboard order/persistence/rollback/mobile; import queue validation/duplicates/admin UI')
 await browser.close()
})().catch(e=>{console.error(e);process.exit(1)})
