const { chromium } = require('playwright')
const assert = require('node:assert/strict')
;(async () => {
 const browser=await chromium.launch({headless:true})
 const page=await browser.newPage({viewport:{width:1500,height:1200}}), errors=[]
 page.on('pageerror',e=>errors.push(e.message))
 await page.clock.setFixedTime(new Date('2026-10-05T12:00:00Z'))
 await page.route('https://fonts.googleapis.com/**',r=>r.fulfill({contentType:'text/css',body:''}))
 const S={weights:{lead:5,pre:10,funnel:20,follow:15,close:35,post:10,fin:5},officialDeduct:10,months:{}}
 const deals=[{id:1,no:'STUCK',name:'متوقف',entry:'1405/05/01',stageChangedAt:'1405/07/01',month:6,funnel:'advance',amount:'100000000',settle:'cash',stages:['lead','pre']},{id:2,no:'WON',name:'بسته',entry:'1405/07/05',saleDate:'1405/07/05',month:6,funnel:'won',amount:'100000000',settle:'cash',stages:['lead','pre','funnel','follow','close','post','fin']}]
 let full={fy:'1405',people:[{id:1,name:'آزمایش',role:'sales',comp:'fixed',S,inv:deals,invY:{1405:deals}}],years:{1405:{}}}
 let writes=[],google=[]
 await page.route('**/api/**',async r=>{
  const url=new URL(r.request().url()), post=r.request().method()==='POST'
  if(url.pathname==='/api/state') { if(post){full=r.request().postDataJSON();writes.push(full)} return r.fulfill({json:{ok:true,full}}) }
  if(url.pathname==='/api/ui-layout') return r.fulfill({json:{ok:true,order:[]}})
  if(url.pathname.startsWith('/api/ai/google/')) { if(post)google.push(r.request().postDataJSON());return r.fulfill({json:{ok:true,enabled:false,configured:post}}) }
  return r.fulfill({json:{ok:true}})
 })
 const url='http://127.0.0.1:5183/tests/browser/index.html'
 console.log('Load ledger'); await page.goto(url);await page.getByRole('grid').waitFor()
 assert.equal(await page.locator('[data-colk="role"]').count(),0)
 assert.equal(await page.locator('[data-colk="date"]').count(),1)
 assert.equal(await page.locator('[data-colk="change"]').count(),1)
 const engine=page.getByRole('region',{name:'مونتاژ موتور و هفت مرحلهٔ فروش'})
 await page.emulateMedia({reducedMotion:'reduce'})
 await engine.getByLabel('معاملهٔ C4',{exact:true}).selectOption('0:2')
 await page.waitForFunction(()=>document.querySelector('section[aria-label="مونتاژ موتور و هفت مرحلهٔ فروش"] img')?.getAttribute('src')?.endsWith('frame-121.webp'))
 assert.equal(writes.length,0)
 assert.equal(await engine.locator('[data-activated="true"]').count(),7)
 await page.getByText('فروش روزانهٔ ماه جاری',{exact:true}).click()
 await page.locator('[data-bklit-sales-chart] .visx-brush').waitFor()
 assert.ok(await page.locator('[data-bklit-sales-chart] svg').count() >= 2)
 console.log('Stagnation filter'); await page.getByRole('button',{name:/توقف بیش از ۴۰ روز/}).click()
 assert.equal(await page.locator('[data-order-row]').count(),1)
 const row=page.locator('[data-order-row]').first()
 await row.getByRole('checkbox',{name:'ایجاد لید 5٪'}).uncheck()
 assert.equal(await page.getByRole('dialog').count(),0)
 await page.waitForTimeout(1000)
 assert.ok(writes.length);assert.ok(!writes.at(-1).people[0].inv[0].stages.includes('lead'))
 console.log('Stagnation filter'); await page.getByRole('button',{name:/توقف بیش از ۴۰ روز/}).click()
 const won=page.locator('[data-order-row="1:2"]')
 console.log('Approval'); await won.getByRole('button',{name:'سند مالی',exact:true}).click()
 const approval=page.locator('form[aria-label="تصویب سند"]')
 await approval.waitFor()
 assert.equal(await approval.getByRole('progressbar').getAttribute('aria-valuenow'),'20')
 assert.equal(await approval.getByLabel('مقدار پورسانت نقد',{exact:true}).inputValue(),'0')
 await approval.getByLabel('مقدار پورسانت نقد',{exact:true}).focus()
 await approval.getByLabel('مقدار پورسانت معلق',{exact:true}).focus()
 await approval.getByLabel('تاریخ ثبت سند',{exact:true}).focus()
 assert.equal(await approval.getByRole('progressbar').getAttribute('aria-valuenow'),'60')
 await page.screenshot({path:'/workspace/scratch/aromin40-desktop.png',fullPage:true})
 await page.setViewportSize({width:390,height:844})
 await page.screenshot({path:'/workspace/scratch/aromin40-mobile.png',fullPage:true})
 await page.goto(url+'?view=google')
 const key=page.getByLabel('کلید API',{exact:true});await key.waitFor()
 assert.equal(await key.getAttribute('type'),'password')
 await key.fill('A'.repeat(39));await page.getByRole('button',{name:'آزمایش اتصال'}).click()
 await page.getByText('اتصال Google موفق بود.').waitFor()
 await page.getByRole('button',{name:'ذخیره',exact:true}).click()
 await page.getByText('تنظیمات دستیار ذخیره شد.').waitFor()
 assert.equal(await key.inputValue(),'');assert.equal(google.length,2)
 assert.equal(await page.evaluate(()=>JSON.stringify(localStorage).includes('A'.repeat(39))),false)
 assert.deepEqual(errors,[])
 console.log('PASS: inline stages/save, date/change columns, >40 day filter, real brush/three series, approval progress, RTL mobile, secure Google settings')
 await browser.close()
})().catch(e=>{console.error(e);process.exit(1)})
